version: '3.8'
services:
  api:
    image: arnab/nest-chat-app
    depends_on:
      - db
    ports:
      - '8080:8080'
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatappdb
